services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.1
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.6.1
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://0.0.0.0:29092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

  kafka-init:
    image: confluentinc/cp-kafka:7.6.1
    container_name: kafka-init
    depends_on:
      - kafka
    entrypoint: ["/bin/sh", "-c"]
    command: >
      "
      cub kafka-ready -b kafka:9092 1 30 &&
      kafka-topics --bootstrap-server kafka:9092 --create --if-not-exists --topic aggregated-state-topic --partitions 1 --replication-factor 1 &&
      echo 'Kafka topic is ready.'
      "

  mongo:
    image: mongo:7
    container_name: mongo
    ports:
      - "27017:27017"

  history-archive-service:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: history-archive-service
    depends_on:
      - mongo
      - kafka
      - kafka-init
    environment:
      MONGO_URI: mongodb://mongo:27017
      MONGO_DB_NAME: history_archive_db
      MONGO_COLLECTION_NAME: state_history
      KAFKA_BROKER: kafka:9092
      KAFKA_TOPIC: aggregated-state-topic
      KAFKA_GROUP_ID: history-archive-group
      KAFKA_AUTO_OFFSET_RESET: earliest
